// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package daemon

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type CaptureExArg struct {
	Buf     uint64
	Num     uint64
	Written uint64
	Ssl     uint64
}

type CaptureGoReadArg struct {
	Buf  uint64
	Conn uint64
}

type CaptureTcpRecvArg struct {
	Sk     uint64
	Buf    uint64
	BufLen uint32
	_      [4]byte
}

type CaptureWriteArg struct {
	Buf uint64
	Len uint32
	_   [4]byte
	Ssl uint64
}

// LoadCapture returns the embedded CollectionSpec for Capture.
func LoadCapture() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CaptureBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Capture: %w", err)
	}

	return spec, err
}

// LoadCaptureObjects loads Capture and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*CaptureObjects
//	*CapturePrograms
//	*CaptureMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadCaptureObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadCapture()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// CaptureSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CaptureSpecs struct {
	CaptureProgramSpecs
	CaptureMapSpecs
}

// CaptureSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CaptureProgramSpecs struct {
	KprobeTcpRecvmsgEntry *ebpf.ProgramSpec `ebpf:"kprobe_tcp_recvmsg_entry"`
	KprobeTcpRecvmsgRet   *ebpf.ProgramSpec `ebpf:"kprobe_tcp_recvmsg_ret"`
	KprobeTcpSendmsg      *ebpf.ProgramSpec `ebpf:"kprobe_tcp_sendmsg"`
	UprobeGoTlsReadEntry  *ebpf.ProgramSpec `ebpf:"uprobe_go_tls_read_entry"`
	UprobeGoTlsReadRet    *ebpf.ProgramSpec `ebpf:"uprobe_go_tls_read_ret"`
	UprobeGoTlsWrite      *ebpf.ProgramSpec `ebpf:"uprobe_go_tls_write"`
	UprobeSslReadEntry    *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read_entry"`
	UprobeSslReadExEntry  *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read_ex_entry"`
	UprobeSslReadExRet    *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read_ex_ret"`
	UprobeSslReadRet      *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read_ret"`
	UprobeSslWriteEntry   *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write_entry"`
	UprobeSslWriteExEntry *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write_ex_entry"`
	UprobeSslWriteExRet   *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write_ex_ret"`
	UprobeSslWriteRet     *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write_ret"`
}

// CaptureMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CaptureMapSpecs struct {
	AgentPids        *ebpf.MapSpec `ebpf:"agent_pids"`
	CandidateEmitted *ebpf.MapSpec `ebpf:"candidate_emitted"`
	Events           *ebpf.MapSpec `ebpf:"events"`
	ExArgs           *ebpf.MapSpec `ebpf:"ex_args"`
	GoReadArgs       *ebpf.MapSpec `ebpf:"go_read_args"`
	TcpFlows         *ebpf.MapSpec `ebpf:"tcp_flows"`
	TcpRecvArgs      *ebpf.MapSpec `ebpf:"tcp_recv_args"`
	WriteArgs        *ebpf.MapSpec `ebpf:"write_args"`
}

// CaptureObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadCaptureObjects or ebpf.CollectionSpec.LoadAndAssign.
type CaptureObjects struct {
	CapturePrograms
	CaptureMaps
}

func (o *CaptureObjects) Close() error {
	return _CaptureClose(
		&o.CapturePrograms,
		&o.CaptureMaps,
	)
}

// CaptureMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadCaptureObjects or ebpf.CollectionSpec.LoadAndAssign.
type CaptureMaps struct {
	AgentPids        *ebpf.Map `ebpf:"agent_pids"`
	CandidateEmitted *ebpf.Map `ebpf:"candidate_emitted"`
	Events           *ebpf.Map `ebpf:"events"`
	ExArgs           *ebpf.Map `ebpf:"ex_args"`
	GoReadArgs       *ebpf.Map `ebpf:"go_read_args"`
	TcpFlows         *ebpf.Map `ebpf:"tcp_flows"`
	TcpRecvArgs      *ebpf.Map `ebpf:"tcp_recv_args"`
	WriteArgs        *ebpf.Map `ebpf:"write_args"`
}

func (m *CaptureMaps) Close() error {
	return _CaptureClose(
		m.AgentPids,
		m.CandidateEmitted,
		m.Events,
		m.ExArgs,
		m.GoReadArgs,
		m.TcpFlows,
		m.TcpRecvArgs,
		m.WriteArgs,
	)
}

// CapturePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadCaptureObjects or ebpf.CollectionSpec.LoadAndAssign.
type CapturePrograms struct {
	KprobeTcpRecvmsgEntry *ebpf.Program `ebpf:"kprobe_tcp_recvmsg_entry"`
	KprobeTcpRecvmsgRet   *ebpf.Program `ebpf:"kprobe_tcp_recvmsg_ret"`
	KprobeTcpSendmsg      *ebpf.Program `ebpf:"kprobe_tcp_sendmsg"`
	UprobeGoTlsReadEntry  *ebpf.Program `ebpf:"uprobe_go_tls_read_entry"`
	UprobeGoTlsReadRet    *ebpf.Program `ebpf:"uprobe_go_tls_read_ret"`
	UprobeGoTlsWrite      *ebpf.Program `ebpf:"uprobe_go_tls_write"`
	UprobeSslReadEntry    *ebpf.Program `ebpf:"uprobe_ssl_read_entry"`
	UprobeSslReadExEntry  *ebpf.Program `ebpf:"uprobe_ssl_read_ex_entry"`
	UprobeSslReadExRet    *ebpf.Program `ebpf:"uprobe_ssl_read_ex_ret"`
	UprobeSslReadRet      *ebpf.Program `ebpf:"uprobe_ssl_read_ret"`
	UprobeSslWriteEntry   *ebpf.Program `ebpf:"uprobe_ssl_write_entry"`
	UprobeSslWriteExEntry *ebpf.Program `ebpf:"uprobe_ssl_write_ex_entry"`
	UprobeSslWriteExRet   *ebpf.Program `ebpf:"uprobe_ssl_write_ex_ret"`
	UprobeSslWriteRet     *ebpf.Program `ebpf:"uprobe_ssl_write_ret"`
}

func (p *CapturePrograms) Close() error {
	return _CaptureClose(
		p.KprobeTcpRecvmsgEntry,
		p.KprobeTcpRecvmsgRet,
		p.KprobeTcpSendmsg,
		p.UprobeGoTlsReadEntry,
		p.UprobeGoTlsReadRet,
		p.UprobeGoTlsWrite,
		p.UprobeSslReadEntry,
		p.UprobeSslReadExEntry,
		p.UprobeSslReadExRet,
		p.UprobeSslReadRet,
		p.UprobeSslWriteEntry,
		p.UprobeSslWriteExEntry,
		p.UprobeSslWriteExRet,
		p.UprobeSslWriteRet,
	)
}

func _CaptureClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed capture_bpfeb.o
var _CaptureBytes []byte
