// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package daemon

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type SslTraceExArg struct {
	Buf     uint64
	Num     uint64
	Written uint64
}

type SslTraceWriteArg struct {
	Buf uint64
	Len uint32
	_   [4]byte
}

// LoadSslTrace returns the embedded CollectionSpec for SslTrace.
func LoadSslTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SslTraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load SslTrace: %w", err)
	}

	return spec, err
}

// LoadSslTraceObjects loads SslTrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SslTraceObjects
//	*SslTracePrograms
//	*SslTraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSslTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSslTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SslTraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SslTraceSpecs struct {
	SslTraceProgramSpecs
	SslTraceMapSpecs
}

// SslTraceSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SslTraceProgramSpecs struct {
	UprobeSslReadEntry    *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read_entry"`
	UprobeSslReadExEntry  *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read_ex_entry"`
	UprobeSslReadExRet    *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read_ex_ret"`
	UprobeSslReadRet      *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read_ret"`
	UprobeSslWriteEntry   *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write_entry"`
	UprobeSslWriteExEntry *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write_ex_entry"`
	UprobeSslWriteExRet   *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write_ex_ret"`
	UprobeSslWriteRet     *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write_ret"`
}

// SslTraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SslTraceMapSpecs struct {
	AgentPids *ebpf.MapSpec `ebpf:"agent_pids"`
	Events    *ebpf.MapSpec `ebpf:"events"`
	ExArgs    *ebpf.MapSpec `ebpf:"ex_args"`
	WriteArgs *ebpf.MapSpec `ebpf:"write_args"`
}

// SslTraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSslTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type SslTraceObjects struct {
	SslTracePrograms
	SslTraceMaps
}

func (o *SslTraceObjects) Close() error {
	return _SslTraceClose(
		&o.SslTracePrograms,
		&o.SslTraceMaps,
	)
}

// SslTraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSslTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type SslTraceMaps struct {
	AgentPids *ebpf.Map `ebpf:"agent_pids"`
	Events    *ebpf.Map `ebpf:"events"`
	ExArgs    *ebpf.Map `ebpf:"ex_args"`
	WriteArgs *ebpf.Map `ebpf:"write_args"`
}

func (m *SslTraceMaps) Close() error {
	return _SslTraceClose(
		m.AgentPids,
		m.Events,
		m.ExArgs,
		m.WriteArgs,
	)
}

// SslTracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSslTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type SslTracePrograms struct {
	UprobeSslReadEntry    *ebpf.Program `ebpf:"uprobe_ssl_read_entry"`
	UprobeSslReadExEntry  *ebpf.Program `ebpf:"uprobe_ssl_read_ex_entry"`
	UprobeSslReadExRet    *ebpf.Program `ebpf:"uprobe_ssl_read_ex_ret"`
	UprobeSslReadRet      *ebpf.Program `ebpf:"uprobe_ssl_read_ret"`
	UprobeSslWriteEntry   *ebpf.Program `ebpf:"uprobe_ssl_write_entry"`
	UprobeSslWriteExEntry *ebpf.Program `ebpf:"uprobe_ssl_write_ex_entry"`
	UprobeSslWriteExRet   *ebpf.Program `ebpf:"uprobe_ssl_write_ex_ret"`
	UprobeSslWriteRet     *ebpf.Program `ebpf:"uprobe_ssl_write_ret"`
}

func (p *SslTracePrograms) Close() error {
	return _SslTraceClose(
		p.UprobeSslReadEntry,
		p.UprobeSslReadExEntry,
		p.UprobeSslReadExRet,
		p.UprobeSslReadRet,
		p.UprobeSslWriteEntry,
		p.UprobeSslWriteExEntry,
		p.UprobeSslWriteExRet,
		p.UprobeSslWriteRet,
	)
}

func _SslTraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ssltrace_bpfeb.o
var _SslTraceBytes []byte
